export enum Category {
  all = "all",
  // vegetables = "vegetables",
  // dairy = "dairy",
  // fruits = "fruits",
  // seafood = "seafood",
  // meat = "meat",
  // beverage = "beverage",
  pestControl = "pest control",
  misc = "misc",
  food = "food",
  publications = "publications",
  app = "app",
  toys = "toys",
  health = "health",
  clothing = "clothing",
}
